import {
  Card,
  CardContent,
  CardMedia,
  CircularProgress,
  Divider,
  Grid,
  Stack,
  Typography,
} from "@mui/material";
import { Box } from "@mui/system";
import React, { useState } from "react";

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allpost, setAllPost] = useState("");

  return (
    <Box sx={{ width: "80%", margin: "10px auto" }}>
      <Stack direction="column" spacing={1}>
        <Typography variant="h6">The Community Showcase</Typography>
        <Typography variant="body2" sx={{ fontFamily: "monospace" }}>
          Browse through a collection of imaginative and visually stunning
          images generated by AI
        </Typography>
      </Stack>
      {loading ? (
        <div style={{ display: "flex", justifyContent: "center" }}>
          <CircularProgress />
        </div>
      ) : (
        <Grid container direction="row" spacing={1}>
          {allpost.length > 0 ? (
            <Grid>
              <Card
                elevation={3}
                sx={{ width: 380, height: 500, borderRadius: "20px" }}
              >
                <CardMedia
                  component="img"
                  alt="AI"
                  height="300"
                  image=""
                  sx={{
                    objectFit: "cover",
                    objectPosition: "top",
                    transition: "0.4s ease",
                    borderStartStartRadius: "20px",
                    "&:hover": {
                      transform: "scale(1.10)",
                      cursor: "pointer",
                    },
                  }}
                />
                <Divider />
                <CardContent>
                  <Typography gutterBottom variant="h5" component="div">
                    "Any"
                  </Typography>
                </CardContent>
              </Card>
            </Grid>
          ) : (
            <Typography
              variant="h6"
              sx={{
                bgcolor: "skyblue",
                borderRadius: "20px",
                marginTop: "50px",
                padding: "5px",
              }}
            >
              NO POST FOUND
            </Typography>
          )}
        </Grid>
      )}
    </Box>
  );
};

export default Home;
